---
# Find available solutions on <analytics.fold.it>
- hosts: analytics.fold.it
  remote_user: pierce
  force_handlers: yes
  vars:
    - top_paths: top-solution-paths.txt
    - puzzles_with_all: puzzles-with-all.txt
  vars_files:
    - vars/main.yml
  tasks:
    # - name: Find available 'top/' solutions
    #   script: bin/find-top-solutions > ~/{{ top_paths }}
    #
    # - name: Fetch list of available top solution files
    #   fetch: src=~/{{ top_paths }} dest={{ repo.loc }}/{{ top_paths }} flat=yes
    #
    # - name: Delete the file with top solution files
    #   file: path=~/{{ top_paths }} state=absent

    - name: Find puzzles with 'all/' directory
      script: bin/find-puzzles-with-all > ~/{{ puzzles_with_all }}

    - name: Fetch list of available puzzles with 'all/'
      fetch: src=~/{{ puzzles_with_all }} dest={{ repo.loc }}/{{ puzzles_with_all }} flat=yes

    - name: Delete the file listing puzzles with 'all/'
      file: path=~/{{ puzzles_with_all }} state=absent

    - name: Find available 'all/' solutions puzzle-by-puzzle
      shell: touch puzzle-{{ item }}-all.txt
      with_lines: "{{ repo.loc }}/{{ puzzles_with_all }}"

    # - name: Fetch list of solution files for each puzzle with 'all/'
    #   fetch: src=~/puzzle-{{ item }}-all.txt dest={{ repo.loc }}/puzzle-{{ item }}-all.txt flat=yes
    #   with_lines: "{{ repo.loc }}/{{ puzzles_with_all }}"
    #
    # - name: Delete files listing solution paths for each puzzle with 'all/'
    #   command: rm ~/puzzle-*-all.txt
