---
# Find available solutions on <analytics.fold.it>
- hosts: analytics.fold.it
  remote_user: pierce
  vars:
    - paths_dir: "{{ repo.loc }}/available-solutions"
    - top_paths: top-solution-paths.txt
    - all_paths: all-solution-paths.txt
  vars_files:
    - vars/main.yml
  tasks:
    - name: Ensure dest directory exists
      file: path={{ paths_dir }} state=directory
    - include: tasks/find_top_solutions.yml
    - include: tasks/find_all_solutions.yml

- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/install_foldit_extractor.yml
