---
# Find available solutions on <analytics.fold.it>
- hosts: analytics.fold.it
  remote_user: pierce
  force_handlers: yes
  vars:
    - top_paths: top-solution-paths.txt
    - puzzles_with_all: puzzles-with-all.txt
  vars_files:
    - vars/main.yml
  tasks:
    - name: Find available 'top/' solutions
      script: bin/find-top-solutions > ~/{{ top_paths }}

    - name: Fetch list of available top solution files
      fetch: src=~/{{ top_paths }} dest={{ repo.loc }}/{{ top_paths }} flat=yes

    - name: Delete the file with top solution files
      file: path=~/{{ top_paths }} state=absent

    - name: Find puzzles with 'all/' directory
      script: bin/find-puzzles-with-all
      register: find_puzzles_with_all_output

    - name: Find all solutions for each puzzle
      script: bin/find-all-solutions {{ item }} > ~/puzzle-{{ item }}-all.txt
      with_items: "{{ find_puzzles_with_all_output.stdout_lines }}"

    - name: Fetch lists of solution files for each puzzle with 'all/'
      fetch: src=~/puzzle-{{ item }}-all.txt dest={{ repo.loc }}/puzzle-{{ item }}-all.txt flat=yes

    - name: Delete files of solution filepaths for each puzzle with 'all/'
      command: rm ~/puzzle-*-all.txt
