---
# Find available solutions on <analytics.fold.it>
- hosts: analytics.fold.it
  remote_user: pierce
  force_handlers: yes
  vars:
    - top_paths: top-solution-paths.txt
    - all_paths: all-solution-paths.txt
  tasks:
    - name: Find available 'top/' solutions
      script: bin/find-top-solutions > ~/{{ top_paths }}
      args:
        executable: /bin/bash
      async: 20*60
      poll: 5*60
      notify:
        - clean up

    - name: Find available 'all/' solutions
      script: bin/find-all-solutions > ~/{{ all_paths }}
      args:
        executable: /bin/bash
      async: 20*60
      poll: 5*60
      notify:
        - clean up

    - name: Retrieve available solutions
      fetch: src=~/{{ item }} dest={{ item }} flat=yes
      with_items:
        - "{{ top_paths }}"
        - "{{ all_paths }}"

  handlers:
    - name: clean up
      file: path={{ item }} state=absent
      with_items:
        - "{{ top_paths }}"
        - "{{ all_paths }}"
