---
# ansible-playbook push.yml
# ansible-playbook push.yml -e bundle_file=1510551071.json
- hosts: localhost
  connection: local
  vars:
    bundle_id: "{{ ansible_date_time.epoch }}"
    bundle_file: "{{ workload_dir }}/{{ bundle_id }}.json"
  vars_files:
    - vars/main.yml
  tasks:
    - name: Determine if bundle file already exists
      stat: path={{ bundle_file }}
      register: bundle_file_stat

    - debug: var=bundle_file_stat

    - include: tasks/bundle_workload.yml
      when: not bundle_file_stat.stat.exists

    - name: Push bundle to S3
      shell: source ~/.profile && push.py {{ bundle_file }}
      args:
        executable: /bin/bash

    - name: Clean up by removing bundle file
      file: path={{ bundle_file }} state=absent
