---
- hosts: foldit
  vars:
    - state: present
  vars_files:
    - vars/main.yml
  tasks:
    - name: Manage crontab to scrape solution files
      cron:
        name: "scrape foldit solutions"
        minute: "0"
        hour: "0"
        job: "source ~/.profile && cd {{ repo.loc }} && scrape.py {{ workload_dir }} {{ n_batches_per_push }}
        user: "{{ ansible_user_id }}"
        state: "{{ state }}"
