---
# Iterate through the workload on <analytics.fold.it>
# $ ansible-playbook scrape-solutions.yml -e workload=solution-filepaths.txt
- hosts: analytics.fold.it
  remote_user: pierce
  vars_files:
    - vars/main.yml
  vars:
    install_scraper: no
  tasks:
    - name: include: tasks/install_scraper.yml
      when: install_scraper
    - include: tasks/get_solutions.yml

- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/append_new_solutions.yml
    - include: tasks/push_to_cloud.yml
