---
# Find available solutions on <analytics.fold.it>
- hosts: analytics.fold.it
  remote_user: pierce
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/find_top_solutions.yml
    - include: tasks/find_all_solutions.yml

# Create the workload on <foldit>
- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/create_workload.yml

# Iterate through the workload on <analytics.fold.it>
- hosts: analytics.fold.it
  remote_user: pierce
  vars_files:
    - vars/main.yml
  tasks:
    - name: Go get latest version of foldit program
      local_action: shell go build -o bin/foldit github.com/pedmiston/foldit

    - name: Load available workloads
      local_action: shell ls {{ workload_dir }} | head -n 2
      register: workload_filenames

    - name: Get solutions in batches
      include: tasks/get_solutions.yml
      with_items: "{{ workload_filenames.stdout_lines }}"
      when: workload_filenames.stdout_lines | length > 0
