---
# Create the workload on <foldit>
- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/create_workload.yml

# Iterate through the workload on <analytics.fold.it>
- hosts: analytics.fold.it
  remote_user: pierce
  vars_files:
    - vars/main.yml
  tasks:
    - include_vars: file=vars/run_id.yml
    - include: tasks/scrape_solutions.yml

# Cleanup
- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - include_vars: file=vars/run_id.yml
    - include: tasks/cleanup.yml
