---
# Iterate through the workload on <analytics.fold.it>
# $ ansible-playbook scrape-solutions.yml -e workload=solution-filepaths.txt
- hosts: analytics.fold.it
  remote_user: pierce
  vars_files:
    - vars/main.yml
  vars:
    install_scraper: no
  tasks:
    - include: tasks/install_scraper.yml
      when: install_scraper
    - include: tasks/get_solutions.yml
