---
# Initiate run by setting the run id
- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/initiate_run.yml
      when: not retry

# Find available solutions on <analytics.fold.it>
- hosts: analytics.fold.it
  remote_user: pierce
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/load_run_id.yml
    - include: tasks/find_available_solutions.yml

# Create the workload on <foldit>
- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/load_run_id.yml
    - include: tasks/create_workload.yml

# Iterate through the workload on <analytics.fold.it>
- hosts: analytics.fold.it
  remote_user: pierce
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/load_run_id.yml
    - include: tasks/scrape_solutions.yml
 
# Cleanup
- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/load_run_id.yml
    - include: tasks/cleanup.yml
