---
- hosts: analytics.fold.it
  remote_user: pierce
  force_handlers: yes
  vars:
    - top_paths: top-solution-paths.txt
    - all_paths: all-solution-paths.txt
  vars_files:
    - vars/main.yml
  tasks:
    - name: Find available 'top/' solutions
      script: bin/find-top-solutions > {{ repo.loc }}/{{ top_paths }}
      args:
        executable: /bin/bash
      async:
      notify:
        - clean up

    - name: Find available 'all/' solutions
      script: bin/find-all-solutions > {{ repo.loc }}/{{ all_paths }}
      args:
        executable: /bin/bash
      async:
      notify:
        - clean up

    - name: Retrieve available solutions
      fetch: src=~/{{ item }} dest={{ item }} flat=yes
      with_items:
        - "{{ top_paths }}"
        - "{{ all_paths }}"

  handlers:
    - name: clean up
      file: path={{ item }} state=absent
      with_items:
        - "{{ top_paths }}"
        - "{{ all_paths }}"
