---
# Find available solutions on <analytics.fold.it>
# - hosts: analytics.fold.it
#   remote_user: pierce
#   vars_files:
#     - vars/main.yml
#   tasks:
#     - include: tasks/find_top_solutions.yml
#     - include: tasks/find_all_solutions.yml

# Create the workload on <foldit>
- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/create_workload.yml

# Iterate through the workload on <analytics.fold.it>
- hosts: analytics.fold.it
  remote_user: pierce
  vars_files:
    - vars/main.yml
  tasks:
    - name: Load available workloads
      local_action: command ls {{ workload_dir }} -name "*.txt"
      register: workload_filenames

    - include: tasks/get_solutions.yml
      with_items: "{{ workload_filenames.stdout_lines }}"
      when: len(workload_filenames.stdout_lines) > 0
