---
- hosts: foldit
  become: yes
  vars_files:
      - vars/main.yml
      - vars/secrets.yml
  tasks:
    - include: tasks/setup_foldit.yml
      when: "host is not defined or host == 'foldit'"

- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
    - vars/secrets.yml
  tasks:
    - include: tasks/setup_localhost.yml
      when: "host is not defined or host == 'localhost'"
