---
- hosts: foldit
  become: yes
  vars_files:
      - vars/main.yml
      - vars/secrets.yml
  tasks:
    - name: Ensure aptitude is installed
      apt: name=aptitude state=present

    - name: Upgrade everything
      apt: upgrade=yes update_cache=yes

    - name: Clone/update foldit-server repo
      git:
        repo: "{{ repo.url }}"
        dest: "{{ repo.loc }}"

    - name: Manage crontab to update the repo
      cron:
        name: "update foldit-server repo"
        minute: "0"
        hour: "0"
        job: "cd {{ repo.loc }} && git pull -q"
        user: "{{ ansible_user_id }}"

    - name: Install MySQL
      apt: name=mysql-server

    - name: Configure MySQL
      include_role:
        name: geerlingguy.mysql
      vars:
        mysql_root_password: "{{ mysql_root_password }}"
        mysql_databases:
          - name: "{{ mysql_db_name }}"
        mysql_users:
          - name: foldit
            host: "%"
            password: "{{ mysql_foldit_password }}"
            priv: "{{ mysql_db_name }}.*:ALL"
