---
# Configure the foldit server and mirror the same environment locally.
#
# Usage:
#   ansible-playbook setup.yml
#   ansible-playbook setup.yml -e host=foldit      # run setup on foldit only
#   ansible-playbook setup.yml -e host=localhost   # run setup on localhost only
#
# Requirements:
#   export ANSIBLE_VAULT_PASSWORD_FILE=/path/to/my/vault-pass.txt
- hosts: foldit
  become: yes
  become_user: pierce
  vars_files:
      - vars/main.yml
      - vars/secrets.yml
  tasks:
    - include_tasks: tasks/setup_foldit.yml
      when: "host is not defined or host == 'foldit'"

- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
    - vars/secrets.yml
  tasks:
    - include_tasks: tasks/setup_localhost.yml
      when: "host is not defined or host == 'localhost'"
