---
- hosts: foldit
  become: yes
  vars_files:
      - vars/main.yml
      - vars/secrets.yml
  tasks:
    - name: Ensure aptitude is installed
      apt: name=aptitude state=present

    - name: Upgrade everything
      apt: upgrade=yes update_cache=yes

    - name: Clone/update foldit-server repo
      git:
        repo: "{{ repo.url }}"
        dest: "{{ repo.loc }}"

    - include: tasks/install_mysql.yml
    - include: tasks/install_foldit_extractor.yml

    # TODO: setup py venv
    # TODO: template .profile
