---
# Create the workload on <foldit>
- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - name: Clear workload directory of prior workloads
      shell: find {{ workload_dir }} -type f ! -name "*.*" -exec rm {} \;
      ignore_errors: yes

    - name: Sort lists of available and completed solutions
      command: sort -o {{ item[0] }}/{{ item[1] }} {{ item[0] }}/{{ item[1] }}
      with_nested:
        - [ "{{ available_dir }}", "{{ completed_dir }}" ]
        - [ "{{ top_solutions }}", "{{ all_solutions }}" ]

    - name: Filter new solutions from available
      shell: comm -23 {{ available_dir }}/{{ item }} {{ completed_dir }}/{{ item }} > {{ remaining_dir }}/{{ item }}
      with_items:
        - "{{ top_solutions }}"
        - "{{ all_solutions }}"
    
    - name: Split remaining solutions into batches
      command: split -l {{ batch_size }} {{ item }} batch-{{ item | splitext | first }}-
      args:
        chdir: "{{ remaining_dir }}"
      with_items:
        - "{{ top_solutions }}"
        - "{{ all_solutions }}"

    - name: Move batches to workload directory
      shell: mv {{ remaining_dir }}/batch-* {{ workload_dir }}/
