---
- name: Combine all the batches into a single json data file for the run.
  local_action: shell cat {{ run_dir }}/batch-*.json > {{ data_dir }}/run-{{ run_id }}.json

- name: Combine all the batch errors into a single txt file for the run.
  local_action: shell cat {{ run_dir }}/batch-*-errors.csv > {{ data_dir }}/errors-run-{{ run_id }}.csv

- name: Delete all batch files after they've been combined.
  local_action: shell rm -r {{ run_dir }}/batch*
  when: cleanup

- name: Remove run_id from tmp vars file
  lineinfile:
    path: "{{ run_id_vars_file }}"
    regexp: "^run_id:"
    line: "run_id: {{ run_id }}"
    state: absent
