---

- name: Filter new solutions from available
  shell: source ~/.profile && filter-new-solutions {{ available_dir }}/{{ item }} {{ completed_dir }}/{{ item }} > {{ remaining_dir }}/{{ item }}
  args:
    executable: /bin/bash
  with_items:
    - "{{ top_solutions }}"
    - "{{ all_solutions }}"

- name: Split remaining solutions into batches
  shell: source ~/.profile && cd {{ remaining_dir }} && split-workload {{ item }} {{ batch_size }}
  args:
    executable: /bin/bash
  with_items:
    - "{{ top_solutions }}"
    - "{{ all_solutions }}"
