---
- name: Get info about top solutions file
  local_action: stat path={{ run_dir }}/{{ top_solutions }}
  register: top_solutions_info

- include: tasks/find_top_solutions.yml
  when: not top_solutions_info.stat.exists

- name: Get info about all solutions file
  local_action: stat path={{ run_dir }}/{{ all_solutions }}
  register: all_solutions_info

- include: tasks/find_all_solutions.yml
  when: not all_solutions_info.stat.exists

- name: Combine all available solutions
  local_action: shell cd {{ run_dir }} && cat {{ top_solutions }} {{ all_solutions }} > {{ available_solutions }}
  ignore_errors: yes
