---
- set_fact:
    workload: "{{ item }}"
    results: "{{ item | splitext | first }}.json"

- name: Copy the workload to the analytics server
  copy: src={{ workload_dir }}/{{ workload }} dest=~/{{ workload }}

- name: Run the puzzle solutions through the parsing script
  script: ~/go/bin/foldit -paths ~/{{ workload }} -dest ~/{{ results }}

- name: Download the data
  fetch: src=~/{{ results }} dest={{ data_dir }}/{{ results }} flat=yes
