---
- set_fact:
    workload: "{{ item }}"
    results: "{{ item | splitext | first }}.json"

- name: Copy the workload to the analytics server
  copy: src={{ workload_dir }}/{{ workload }} dest=~/{{ workload }}

- name: Run the puzzle solutions through the parsing script
  shell: ~/foldit ~/{{ workload }} > {{ results }} 2> ~/{{ errors }}

- name: Download the data and any errors
  fetch: src=~/{{ item }} dest={{ results_dir }}/{{ item }} flat=yes
  with_items:
    - "{{ results }}"
    - "{{ errors }}"

- name: Delete leftover files on analytics server
  file: path={{ item }} state=absent
  with_items:
    - "~/{{ results }}"
    - "~/{{ workload }}"

- name: Delete workload files on remote machine
  local_action: file path={{ workload_dir }}/{{ workload }} state=absent
