---
- set_fact:
    workload: "{{ item }}"
    results: "{{ item }}.json"
    errors: "{{ item }}-errors.txt"

- name: Copy the workload to the analytics server
  copy: src={{ run_dir }}/{{ workload }} dest=~/{{ workload }}

- name: Run the puzzle solutions through the parsing script
  shell: ~/bin/foldit ~/{{ workload }} > ~/{{ results }} 2> ~/{{ errors }}

- name: Download the data and any errors
  fetch: src=~/{{ item }} dest={{ run_dir }}/{{ item }} flat=yes
  with_items:
    - "{{ results }}"
    - "{{ errors }}"

- name: Delete leftover files on analytics server
  file: path={{ item }} state=absent
  with_items:
    - "~/{{ workload }}"
    - "~/{{ results }}"
    - "~/{{ errors }}"
  when: cleanup

- name: Delete workload file on foldit machine
  local_action: file path={{ run_dir }}/{{ workload }} state=absent
  when: cleanup
