---
- name: Determine next run id
  shell: source ~/.profile && bin/determine-run-id {{ data_dir }}
  register: run_id_out
  args:
    executable: /bin/bash

- name: Save new run id as ansible fact
  set_fact: run_id={{ run_id_out.stdout }}

- name: Hardcode run id in tmp vars file
  lineinfile:
    path: "{{ tmp_vars_file }}"
    regexp: "^run_id:"
    line: "run_id: {{ run_id }}"

- name: Create data dir for run
  file: path={{ run_dir }} state=directory
