---
- name: Install MySQL
  apt: name=mysql-server

- name: Configure MySQL
  include_role:
    name: geerlingguy.mysql
  become: yes
  become_user: root
  vars:
    mysql_root_password: "{{ mysql_root_password }}"
    mysql_databases:
      - name: "{{ mysql_db_name }}"
      - name: "{{ mysql_db_name }}Test"
    mysql_users:
      - name: foldit
        host: "%"
        password: "{{ mysql_foldit_password }}"
        priv: "{{ mysql_db_name }}.*:ALL"
      - name: foldittest
        host: "%"
        password: "{{ mysql_foldit_password }}"
        priv: "{{ mysql_db_name }}Test.*:ALL"
