---
- include_tasks: tasks/setup_foldit_repo.yml

- name: Create .profile on foldit server via template
  template: src=templates/profile.j2 dest=~/.profile
  vars:
    repo_loc: "{{ repo.loc }}"

- include_tasks: tasks/setup_venv.yml
