---
repo:
  url: "https://github.com/pedmiston/foldit-server.git"
  loc: "~/foldit-server"

mysql_db_name: Foldit

top_solutions: top-solutions.txt
all_solutions: all-solutions.txt

batch_size: 1000

data_dir: "{{ repo.loc }}/data"
available_dir: "{{ data_dir }}/available"
downloaded_dir: "{{ data_dir }}/downloaded"
new_dir: "{{ data_dir }}/new"
