---
repo:
  url: "https://github.com/pedmiston/foldit-server.git"
  loc: "~/foldit-server"

mysql_db_name: Foldit

top_solutions: top-solutions.txt
all_solutions: all-solutions.txt

batch_size: 1000
n_batches_per_push: 100

data_dir: "{{ repo.loc }}/data"
available_dir: "{{ data_dir }}/available"
completed_dir: "{{ data_dir }}/completed"
remaining_dir: "{{ data_dir }}/remaining"
workload_dir: "{{ data_dir }}/workload"
