---
# Find available solutions on <analytics.fold.it>
- hosts: analytics.fold.it
  remote_user: pierce
  vars_files:
    - vars/main.yml
  tasks:
    - name: Find 'top/' solutions
      include: tasks/find_top_solutions.yml
      when: 'type is not defined or type == "top"'

    - name: Find 'all/' solutions
      include: tasks/find_all_solutions.yml
      when: 'type is not defined or type == "all"'
