---
- hosts: foldit
  become: yes
  vars:
    - db_name: Foldit
    - mysql_root_password: "{{ root_password }}"
    - mysql_databases:
        - name: "{{ db_name }}"
    - mysql_users:
        - name: foldit
          host: "%"
          password: "{{ foldit_password }}"
          priv: "{{ db_name }}.*:ALL"
        - name: foldit
          host: "localhost"
          password: "{{ foldit_password }}"
          priv: "{{ db_name }}.*:ALL"
  vars_files:
    - vars/secrets.yml
  pre_tasks:
    - name: Ensure aptitude is installed
      apt: name=aptitude state=present
    - name: Upgrade everything
      apt: upgrade=yes update_cache=yes
    - name: Install MySQL
      apt: name=mysql-server

  roles:
    - { role: geerlingguy.mysql }
