---
- name: Install the scraper on <analytics.fold.it>
  hosts: analytics.fold.it
  remote_user: pierce
  vars_files:
    - vars/main.yml
  tasks:
    - name: Get the latest version of the foldit program
      local_action: shell go get -u {{ scraper_gopath }}

    - name: Build the foldit program
      local_action: shell go build -o {{ scraper }} {{ scraper_gopath }}

    - name: Ensure '~/bin' exists on the analytics server
      file: path=~/bin state=directory

    - name: Move the foldit program to the analytics server
      copy: src={{ scraper }} dest=~/{{ scraper }} mode=u+x

    - name: Remove the local copy of the foldit program
      local_action: file path={{ scraper }} state=absent
