---
# Schedule when to run scrape.py
# Usage:
#   ansible-playbook schedule.yml
#   ansible-playbook schedule.yml -e state=absent  # deactivate
- hosts: foldit
  vars:
    - state: present
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/setup_foldit_repo.yml
    - name: Manage crontab to scrape solution files
      cron:
        name: "scrape foldit solutions"
        minute: "0"
        hour: "22"
        job: "source ~/.profile && cd {{ repo.loc }}/playbooks && scrape.py"
        user: "{{ ansible_user_id }}"
        state: "{{ state }}"
